mattrubin/Authenticator

Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/Authenticator-Bridging-Header.h, Authenticator/Classes/OTPTextFieldCell+TokenForm.h, Authenticator/Classes/OTPTextFieldCell+TokenForm.m, Authenticator/Classes/OTPTokenEditViewController.h, Authenticator/Classes/OTPTokenEditViewController.m, Authenticator/Classes/OTPTokenEntryViewController.m, Authenticator/Classes/OTPTokenFormViewController.h, Authenticator/Classes/OTPTokenFormViewController.m
Refactor token entry and edit screens to rely on a common superclass, but function independently of each other.
=> Refactor Token Forms

Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/OTPSegmentedControlCell+TokenForm.swift, Authenticator/Classes/OTPSegmentedControlCell.swift, Authenticator/Classes/OTPTokenEntryViewController.m
Refactor `OTPSegmentedControlCell` to be configured with a `SegmentedControlRowModel` and expose a `value` property.
=> Refactor segmented control cells

Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/Section.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift
Organize cells and headers in an array of `Section`s rather than nested arrays of cells. This allows section headers to be grouped with each section's cells.
=> Add Section struct

Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/TableViewModel.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenForm.swift, Authenticator/Classes/TokenFormViewController.swift
Wrap each `TokenForm`'s title and sections into a `TableViewModel`. Store the current view model in `TokenFormViewController`, and use it to populate the table view.
=> Table view model

Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/BarButtonViewModel.swift, Authenticator/Classes/OTPScannerViewController.m, Authenticator/Classes/OTPTokenListViewController.swift, Authenticator/Classes/OTPTokenSourceDelegate.h, Authenticator/Classes/TableViewModel.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenForm.swift, Authenticator/Classes/TokenFormViewController.swift
Add `BarButtonViewModel` and use it to configure the bar button items in the `TokenFormViewController`. Also, 	pass form cancellation via the delegate chain, rather than dismissing the form view controller directly.
=> Bar button view model

Authenticator/Classes/OTPSegmentedControlCell+TokenForm.swift, Authenticator/Classes/OTPSegmentedControlCell.swift, Authenticator/Classes/TokenEntryForm.swift
Add a `valueChangedAction` to `SegmentedControlRowModel`, and use it to call `formValuesDidChange()` when the segmented controls change.
=> Segmented control actions

Authenticator/Classes/OTPCell.swift, Authenticator/Classes/OTPTextFieldCell.swift, Authenticator/Classes/TableViewModel.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenForm.swift, Authenticator/Classes/TokenFormViewController.swift
Move `OTPTextFieldCell` focus handling out of the forms and into the view controller.
=> Form focus

Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/FormModels.swift, Authenticator/Classes/Section.swift, Authenticator/Classes/TableViewModel.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenForm.swift, Authenticator/Classes/TokenFormViewController.swift
Genericize `TableViewModel` based on a model family of `RowModel` and `HeaderModel` types.
=> Generic table view model

.hound.yml, .swiftlint.yml, Authenticator.xcodeproj/project.pbxproj, Authenticator/Classes/Colors.swift, Authenticator/Classes/OTPAppDelegate.swift, Authenticator/Classes/OTPProgressRing.swift, Authenticator/Classes/OTPTokenListViewController.swift, Authenticator/Classes/QRScanner.swift, Authenticator/Classes/TableViewModel.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenFormViewController.swift, Authenticator/Classes/TokenRowCell.swift, Authenticator/Classes/TokenScannerViewController.swift
Configure the Xcode project to run [SwiftLint](https://github.com/realm/SwiftLint) on every build, and configure [Hound](https://houndci.com) to run the linter on pull requests.
Many small pieces of code have been refactored to appease the linter. Some SwiftLint rules have been disabled because satisfying them will require more extensive refactoring.
=> SwiftLint and Hound

Authenticator/Classes/OTPAppDelegate.swift, Authenticator/Classes/OTPTokenListViewController.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenScannerViewController.swift
Replace the `TokenEntryForm` and `TokenScannerViewController` delegates with event callbacks.
=> Token Entry Callbacks

Authenticator/Classes/OTPTokenListViewController.swift, Authenticator/Classes/TokenEditForm.swift, Authenticator/Classes/TokenEntryForm.swift, Authenticator/Classes/TokenScannerViewController.swift
- Change `Event`s from exclusive `Save`/`Cancel` to complementary `Save`/`Close`
- Consolidate modal form presentation and dismissal
=> Callback refactoring

README.md
Added information about checking out the project and updating dependencies to the README.
=> "Getting Started" instructions

Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/OTPTokenListViewController.swift, Authenticator/Source/TableDiff.swift, Authenticator/Source/TokenFormViewController.swift, Authenticator/Source/TokenListViewModel.swift, Authenticator/Source/TokenManager.swift, Authenticator/Source/TokenRowModel.swift
Populate the token list with a TokenListViewModel containing an array of row models. Instead of manually updating the token list table view after every change, automatically update the table view whenever the view model changes.
=> Token List View Model

Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/OTPTokenListViewController.swift, Authenticator/Source/TokenListDelegate.swift, Authenticator/Source/TokenListViewModel.swift, Authenticator/Source/TokenManager.swift
Route token list actions from the `OTPTokenListViewController` to the `TokenManager` via the `TokenListDelegate` protocol. Provide all presentation data from the token manager to the view controller via the `TokenListViewModel` and `EphemeralMessage`.
=> Token List Delegate

Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/TokenFormViewController.swift, Authenticator/Source/TokenListViewController.swift, Authenticator/Source/UITableView+ReusableCells.swift
Clean up `TokenListViewController` configuration and use `dequeueReusableCellWithClass(_:)` for cell creation.
=> TokenListViewController Cleanup

Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/ActionHandler.swift, Authenticator/Source/AppModel.swift, Authenticator/Source/AppViewController.swift, Authenticator/Source/AppViewModel.swift, Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/TokenScannerViewController.swift
The `AppModel` holds the application's top-level state and handles top-level `AppAction`s. The app state is used to create an `AppViewModel` which describes the interface state. The `AppViewController` interprets the declarative `AppViewModel` to animate the presentation, transition, and dismissal of various view controllers.
=> AppModel → AppViewModel → AppViewController

Authenticator/Source/AppViewController.swift, Authenticator/Source/TokenList.swift, Authenticator/Source/TokenListDelegate.swift, Authenticator/Source/TokenListViewController.swift
Convert `TokenListDelegate` into `TokenListActionHandler` for handling `TokenList.Action`s.
=> Token list action handler

Authenticator/Source/FormModels.swift, Authenticator/Source/SegmentedControlRowCell.swift, Authenticator/Source/SegmentedControlRowModel.swift, Authenticator/Source/TextFieldRowCell.swift, Authenticator/Source/TextFieldRowModel.swift, Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenEntryForm.swift, Authenticator/Source/TokenFormViewController.swift
- Convert `SegmentedControlRowModel` from protocol to struct
- Convert `TextFieldRowModel` constructors to convenience initializers
- Fix text field delegation
=> Form row models

Authenticator/Source/FormModels.swift, Authenticator/Source/SegmentedControlRow.swift, Authenticator/Source/TextFieldRow.swift, Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenEntryForm.swift, Authenticator/Source/TokenFormRowModels.swift, Authenticator/Source/TokenFormViewController.swift
Add identity values to `Form.HeaderModel` and `Form.RowModel`.
=> Form row identity

Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenEntryForm.swift
Refactor the internals of `TokenEntryForm` and `TokenEditForm`.
=> Form cleanup

Authenticator/Source/ActionHandler.swift, Authenticator/Source/AppModel.swift, Authenticator/Source/AppViewController.swift, Authenticator/Source/AppViewModel.swift, Authenticator/Source/TokenList.swift, Authenticator/Source/TokenListDelegate.swift, Authenticator/Source/TokenListViewController.swift
Route `TokenList` actions and view model updates via the app root component.
=> Token list action handling

Authenticator/Source/AppModel.swift, Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/TokenStore.swift
Refactor code handling token order persistence, and inject a token store's keychain and user defaults via the initializer.
=> Persistence injection

Authenticator/Source/ActionHandler.swift, Authenticator/Source/AppModel.swift, Authenticator/Source/TokenList.swift, Authenticator/Source/TokenListViewController.swift, Authenticator/Source/TokenRowModel.swift, Authenticator/Source/TokenStore.swift
Consolidate `TokenRowModel.Action` and `TokenList.Action`, and change the delete action to delete a given persistent token, rather than the token at a given index.
=> Token Row Actions

Authenticator/Source/TokenListViewController.swift, Authenticator/Source/TokenRowCell.swift
This pattern is used for the other table view cells in the app.
=> Replace TokenRowDelegate with a dispatchAction closure

Authenticator/Source/ActionHandler.swift, Authenticator/Source/AppModel.swift, Authenticator/Source/AppViewController.swift, Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/TokenScannerViewController.swift
Remove the `ActionHandler` protocol, and standardize view controller action handling on the `dispatchAction` closure.
=> Action Handling

Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/Component.swift, Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/Root.swift, Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenEntryForm.swift, Authenticator/Source/TokenList.swift
Add a `Component` protocol to standardize the interfaces of the various components.
=> Component protocol

Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/AppController.swift, Authenticator/Source/OTPAppDelegate.swift
Add `AppController`, which owns and controls the interactions between the store, component, and view.
=> App controller

Authenticator/Source/Root.swift, Authenticator/Source/RootViewController.swift, Authenticator/Source/RootViewModel.swift, Authenticator/Source/TokenListViewController.swift
Rename types nested in `Root`.
=> Type names

Authenticator.xcodeproj/project.pbxproj, CHANGELOG.md
Add a changelog file, following the guidance of [keepachangelog.com](http://keepachangelog.com).
=> Add a changelog

Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/RootViewController.swift
Style navigation bar and toolbar directly, without using `UIAppearance` globals.
=> Bar appearance

.gitmodules, Cartfile, Cartfile.resolved
- Update OneTimePassword to the release version of 2.0
- Update the url for SVProgressHUD
=> Update Dependencies (Again)

Authenticator/Source/AppController.swift, Authenticator/Source/QRScanner.swift, Authenticator/Source/RootViewController.swift, Authenticator/Source/TableDiff.swift, Authenticator/Source/TokenListViewController.swift
Clean up function calls which wrap to multiple lines.
This includes the addition of a `compose` helper to create dispatchers for nested actions.
=> Clean up wrapped function calls

Authenticator/Source/TableViewModel.swift, Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenEntryForm.swift, Authenticator/Source/TokenFormViewController.swift, Authenticator/Source/TokenList.swift, Authenticator/Source/TokenListViewController.swift
- Add ephemeral error messages to the token edit form.
- Use explicit actions to clear the ephemeral messages in the token list and forms
=> Ephemeral messages

Authenticator/Source/AppController.swift, Authenticator/Source/OTPAppDelegate.swift, Authenticator/Source/Root.swift
Add a new action and success and failure callbacks specifically for adding a token from a URL.
=> Add Root.Action.AddTokenFromURL

Authenticator/Source/Root.swift, Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenEntryForm.swift, Authenticator/Source/TokenList.swift
Improve validation error messages in forms and add action-specific failure callbacks with better error messages for keychain errors.
=> Better error messages

.swiftlint.yml, Authenticator/Source/TableDiff.swift, Authenticator/Source/TextFieldRow.swift, Authenticator/Source/TokenFormViewController.swift, Authenticator/Source/TokenRowCell.swift
Update SwiftLint configuration for SwiftLint 0.12.0, and opt in to several new rules.
=> Update SwiftLint configuration

.travis.yml, Authenticator.xcodeproj/project.pbxproj, Authenticator.xcodeproj/xcshareddata/xcschemes/Authenticator.xcscheme, Authenticator/Source/OTPProgressRing.swift, Authenticator/Source/ScannerOverlayView.swift, Cartfile.resolved
Update dependencies, code, and the project file to support Xcode 8 and Swift 2.3 while also maintaining support for Xcode 7.3 and Swift 2.2 (for now).
=> Update for Xcode 8 and Swift 2.3

Authenticator.xcodeproj/project.pbxproj, AuthenticatorTests/TableDiffTests.swift
After checking out #142 it seemed like a good spot for a unit test.
I confirmed that running the test before your changes produced a `.Update` change and failed the test.
=> Unit test for diffing TokenRowModel lists

.travis.yml
Previously, Travis was only building the app. Now that [there are tests][test-pr], Travis should also run the tests.
[test-pr]: https://github.com/mattrubin/Authenticator/pull/143
=> Enable Testing on Travis CI

.mailmap, AUTHORS
Add @beaucollins to the authors file and update the git mailmap.
=> Update the authors list

.swiftlint.yml, Authenticator.xcodeproj/project.pbxproj, Authenticator/Source/ButtonHeaderView.swift, Authenticator/Source/Colors.swift, Authenticator/Source/OTPProgressRing.swift, Authenticator/Source/QRScanner.swift, Authenticator/Source/RootViewController.swift, Authenticator/Source/ScannerOverlayView.swift, Authenticator/Source/SearchField.swift, Authenticator/Source/SegmentedControlRow.swift, Authenticator/Source/TableDiff.swift, Authenticator/Source/TextFieldRow.swift, Authenticator/Source/TokenEditForm.swift, Authenticator/Source/TokenFormViewController.swift, Authenticator/Source/TokenList.swift, Authenticator/Source/TokenListViewController.swift, Authenticator/Source/TokenRowCell.swift, Authenticator/Source/TokenScannerViewController.swift, AuthenticatorTests/TableDiffTests.swift, AuthenticatorTests/TokenListTests.swift
Update the SwiftLint configuration for SwiftLint 0.15, enabling many new rules and disabling some others.
=> Update for SwiftLint 0.15

.travis.yml, Authenticator.xcodeproj/project.pbxproj
Configure Travis to:
- build with Xcode 8.2
- use the project-specified SDK
- build and test on four custom simulators
=> Update Travis Configuration
