.travis.yml

Updated arguments from the [Travis Objective-C docs](http://docs.travis-ci.com/user/languages/objective-c/#Xcode-6.4) to build with Xcode 6.4 for the simulator running iOS 8.4. Also removed a few `before_install` commands which are no longer necessary on the new image.

Configure Travis to build with Xcode 6.4

---

Authenticator/Classes/OTPHeaderView.swift
Authenticator/Classes/OTPSegmentedControlCell+TokenForm.swift
Authenticator/Classes/OTPSegmentedControlCell.swift
Authenticator/Classes/OTPTextFieldCell.swift
Authenticator/Classes/OTPTokenFormViewController.m
Authenticator/Classes/TokenEntryForm.swift

Genericizes `OTPSegmentedControlCell` and `SegmentedControlRowModel` for an equatable `Value` type.
Also converts `preferredHeight` to a property on cell instances, since static stored properties aren't supported on generic types.

Generic segmented control cell

---

Authenticator/Classes/OTPHeaderView.swift
Authenticator/Classes/OTPTextFieldCell.swift
Authenticator/Classes/TokenEditForm.swift
Authenticator/Classes/TokenEntryForm.swift
Authenticator/Classes/TokenForm.swift
Authenticator/Classes/TokenFormViewController.swift

Remove `objc` specifier from protocols, and consolidate table view support methods into an extension on the `TokenForm` protocol.

Swift protocols

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Classes/HeaderViewModel.swift
Authenticator/Classes/OTPHeaderView.swift
Authenticator/Classes/Section.swift
Authenticator/Classes/TableViewModel.swift
Authenticator/Classes/TokenEntryForm.swift
Authenticator/Classes/TokenFormViewController.swift

Add `HeaderViewModel` and use it to configure `OTPHeaderView`. `OTPHeaderViewDelegate` is replaced by an action closure.

Header view models

---

Authenticator/Classes/TableViewModel.swift
Authenticator/Classes/TokenEditForm.swift
Authenticator/Classes/TokenEntryForm.swift
Authenticator/Classes/TokenFormViewController.swift

Within the context of the table view model, the bar button view models can be referred to without the "ViewModel" suffix.

Bar button view model names

---

Authenticator/Classes/OTPTextFieldCell+TokenForm.swift
Authenticator/Classes/OTPTextFieldCell.swift
Authenticator/Classes/TokenEditForm.swift
Authenticator/Classes/TokenEntryForm.swift

Refactor the configuration of text field cells in the forms, and replace the `textFieldCellDidChange` delegate method with a `changeAction` closure.

Text field row models

---

Authenticator/Classes/OTPSegmentedControlCell+TokenForm.swift
Authenticator/Classes/OTPTextFieldCell+TokenForm.swift
Authenticator/Classes/TokenEditForm.swift
Authenticator/Classes/TokenEntryForm.swift

Wrap form state in a private internal `State` struct, instead of using the table view cells to store the state.
Replace `...DidChange` methods with `didSet` observation on the `state`. Specify the initial values for all cells explicitly from the form state.

Form state

---

Authenticator/Classes/OTPCell.swift
Authenticator/Classes/OTPHeaderView.swift
Authenticator/Classes/OTPSegmentedControlCell.swift
Authenticator/Classes/OTPTextFieldCell.swift
Authenticator/Classes/Section.swift
Authenticator/Classes/TableViewModel.swift
Authenticator/Classes/TokenEditForm.swift
Authenticator/Classes/TokenEntryForm.swift
Authenticator/Classes/TokenFormViewController.swift

Populate `TableViewModel` `Section`s with `FormRowModel`s instead of `UITableViewCell`s. The `FormRowModel` enables a mapping from row view models to row cells. Construct cells on demand in the view controller rather than pre-building them in the forms.

Row models to cells

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Classes/ButtonHeaderView.swift
Authenticator/Classes/FormModels.swift
Authenticator/Classes/HeaderViewModel.swift
Authenticator/Classes/Section.swift
Authenticator/Classes/TableViewModel.swift
Authenticator/Classes/TokenEditForm.swift
Authenticator/Classes/TokenEntryForm.swift
Authenticator/Classes/TokenFormViewController.swift

Rename `OTPHeaderView` to `ButtonHeaderView` and `HeaderViewModel` to `ButtonHeaderViewModel`. Rename `FormRowModel` to `Form.RowModel` and create a similar `Form.HeaderModel` enum for specifying and constructing section headers.

Header models

---

Authenticator/Classes/OTPTokenListViewController.swift
Authenticator/Classes/TokenEditForm.swift

Replace the multiple methods of `TokenEditFormDelegate` with a single callback closure that takes an `TokenEditForm.Event` enum value. This allows information associated with the editing of a token (the keychain item) to be captured by the callback closure when the form is created, instead of being manually retained in the form only to be read out by the delegate later.

Replace TokenEditFormDelegate with Event callback

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Source/TableDiff.swift
Authenticator/Source/TextFieldRowCell.swift
Authenticator/Source/TokenEditForm.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenForm.swift
Authenticator/Source/TokenFormViewController.swift

Comparing an old and new table view model with a simple SES algorithm produces a collection of `Change`s, which can be used to automatically call the corresponding animation methods on a `UITableView`. This removes the need to manually trigger the correct animations when the data model changes.

Automatic table view update animations

---

Authenticator/Source/TableViewModel.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenForm.swift
Authenticator/Source/TokenFormViewController.swift

Replace `form(_:didFailWithErrorMessage:)` with an ephemeral `errorMessage` property in `TableViewModel`.

Ephemeral Error Messages

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Source/ActionHandler.swift
Authenticator/Source/MasterPresenter.swift
Authenticator/Source/OTPAppDelegate.swift
Authenticator/Source/TokenEditForm.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenList.swift
Authenticator/Source/TokenScannerViewController.swift

Replace each screen's individual `Event`s and `callback` closures with a single `ActionHandler` which handles `AppAction`s sent from all screens. This is part of an app-wide effort to replace action *functions* with action *types*, which can be compared, serialized, and replayed easily.

ActionHandler

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Source/FormModels.swift
Authenticator/Source/OTPTextFieldCell+TokenForm.swift
Authenticator/Source/SegmentedControlRowCell.swift
Authenticator/Source/SegmentedControlRowModel.swift
Authenticator/Source/TextFieldRowCell.swift
Authenticator/Source/TextFieldRowModel.swift
Authenticator/Source/TokenEditForm.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenForm.swift
Authenticator/Source/TokenFormViewController.swift

Change the actions on form field row models from side-effect-laden closures which modify the form values directly to closures which generate an `Action` containing the new value, which is routed back to the form via delegate.

Form field actions

---

Authenticator/Source/AppViewController.swift
Authenticator/Source/TableViewModel.swift
Authenticator/Source/TokenForm.swift
Authenticator/Source/TokenFormViewController.swift

Remove the `TokenFormViewController`'s reference to the `TokenForm`. Instead, initialize the view controller with an initial view model and a `FormActionHandler`.

Form action handler

---

Authenticator/Source/ActionHandler.swift
Authenticator/Source/AppModel.swift
Authenticator/Source/AppViewController.swift
Authenticator/Source/AppViewModel.swift
Authenticator/Source/TokenForm.swift

Route form view models from the component to the view controller via the `AppViewModel`, and route form actions from the view controller to the component via `AppAction` handling.
The goal of this change is to decouple `TokenForm` and `TokenFormViewController` by having that top-level component/view mediate between them.

Form routing

---

Authenticator/Source/BarButtonViewModel.swift
Authenticator/Source/ButtonHeaderView.swift
Authenticator/Source/FormModels.swift
Authenticator/Source/TableViewModel.swift
Authenticator/Source/TokenEditForm.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenFormViewController.swift

Convert the action attributes of `TableViewModel`, `BarButtonViewModel`,  and `ButtonHeaderViewModel` from closures to `Form.Action`s. These declarative actions follow the same routing as the token forms' field actions, and avoid using opaque closures with side effects and direct references to the form state.

Table view model actions

---

Authenticator/Source/AppModel.swift
Authenticator/Source/TokenEditForm.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenForm.swift
Authenticator/Source/TokenFormViewController.swift

Convert `TokenEntryForm` and `TokenEditForm` to `struct`s.
The forms' `presenter`s are removed, and the `AppModel` is responsible for handling updated view models when form state changes. The forms' `actionHandler`s are removed, and `AppAction`s resulting from form actions are routed via the return value of the form's `handleAction(_:)`.

Form Structs

---

Authenticator/Source/FormModels.swift
Authenticator/Source/SegmentedControlRowCell.swift
Authenticator/Source/SegmentedControlRowModel.swift
Authenticator/Source/TokenFormViewController.swift

This PR re-genericizes `SegmentedControlRowCell` on the type of `Action` dispatched when a segment is selected. It also simplifies `SegmentedControlRowModel` to not expose raw values, and to expose instead a title and action for each segment and a selected segment index. The values represented by the segments become a private detail of the row models, and the values are wrapped in a change action before being passed to the cell.

Segmented control rows

---

Authenticator/Source/OTPAppDelegate.swift
Authenticator/Source/Root.swift

Move ownership of the token store out of the root component and into the app delegate. Use `Effect`s to send changes from the `Root` to the `TokenStore`.

Root Effects

---

Authenticator/Source/OTPAppDelegate.swift
Authenticator/Source/Root.swift
Authenticator/Source/RootViewController.swift
Authenticator/Source/RootViewModel.swift

Convert the `Root` component to a struct, matching the pattern used with the child components. Remove the `AppPresenter` protocol and give the app delegate responsibility for updating the `RootViewController` when the app state changes.

Root component struct

---

Authenticator/Source/TokenListViewController.swift

Every token list view model update – even those without any row changes – was triggering a table view update. As a result, the row animation when a token was deleted was cut short by the (empty) animation set of the next update. The fix is to prevent table updates except when truly necessary.

Restore full token deletion animation

---

Authenticator/Source/OTPProgressRing.swift
Authenticator/Source/ScannerOverlayView.swift
Authenticator/Source/SegmentedControlRow.swift
Authenticator/Source/TextFieldRow.swift
Authenticator/Source/TokenListViewController.swift
Authenticator/Source/TokenRowCell.swift

- Use modern constructors in place of `CGRectMake()` and `CGPointMake()`
- Use `CGRect` extended properties instead of `CGRectGet*()` functions

Modernize CoreGraphics methods

---

Authenticator/Source/RootViewController.swift

Unlike the cases for the entry form and edit form, when updating the view model with a scanner modal, the RootViewController had no check to determine whether a scanner view controller was already presented.

Check if a scanner is visible before presenting another

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Source/AppController.swift
Authenticator/Source/DisplayTime.swift
Authenticator/Source/Root.swift
Authenticator/Source/TokenList.swift
Authenticator/Source/TokenListViewController.swift
Authenticator/Source/TokenListViewModel.swift
Authenticator/Source/TokenRowModel.swift

Add the `DisplayTime` type and use it as a parameter for `TokenList` and `TokenRowModel`, to explicitly specify the time which should be used when rendering their time-based outputs (the progress ring and the time-based generated passwords).

Add a "display time" parameter for time-based rendering

---

README.md

Provide explicit commands for checking out the project and ensure submodules are checked out recursively.
Fixes #112.

Improve the "Getting Started" instructions in the README

---

.swiftlint.yml
Authenticator/Source/OTPAppDelegate.swift
Authenticator/Source/OTPProgressRing.swift
Authenticator/Source/RootViewController.swift
Authenticator/Source/TableDiff.swift
Authenticator/Source/TokenList.swift
Authenticator/Source/TokenListViewController.swift
Authenticator/Source/TokenRowCell.swift

Update SwiftLint configuration to enable additional rules, and make some source changes in response to linter warnings:
- Refactor `OTPProgressRing` to use `CGRect` extension methods instead of legacy free functions.
- Consolidate previously-wrapped function declarations onto single lines.
- Refactor `TokenList.Action` equality to reduce the cyclomatic complexity.
- Selectively disable force-unwrapping warnings for certain initializations of `UIFont`s

Lint Cleanup

---

Authenticator.xcodeproj/project.pbxproj
README.md

Improve the "Getting Started" instructions and add project-wide indentation configuration to the Xcode project.

Improve clean clones

---

Authenticator/Source/AppController.swift
Authenticator/Source/Root.swift
Authenticator/Source/TokenList.swift

- Replace `updateWithPersistentTokens(_:)` mutating functions with actions
- Add success callback actions to effects which modify the `TokenStore`

TokenStore update success callbacks

---

Authenticator/Source/AppController.swift
Authenticator/Source/Root.swift
Authenticator/Source/TokenList.swift
Authenticator/Source/TokenListViewController.swift
Authenticator/Source/TokenStore.swift

- Add failure callback actions to effects which mutate the keychain.
- Catch errors thrown from the keychain and handle them with the failure actions.
- Add error message effects and present ephemeral error messages from the `AppController`.

Handle Keychain errors

---

Authenticator/Source/AppController.swift
Authenticator/Source/Root.swift
Authenticator/Source/TableViewModel.swift
Authenticator/Source/TokenEditForm.swift
Authenticator/Source/TokenEntryForm.swift
Authenticator/Source/TokenFormViewController.swift
Authenticator/Source/TokenList.swift
Authenticator/Source/TokenListViewController.swift
Authenticator/Source/TokenListViewModel.swift

Instead of handling the display of ephemeral success/failure messages separately in each component/view controller, route ephemeral messages via effects to the `AppController`.

Route ephemeral messages via effects

---

Authenticator/Source/TokenFormViewController.swift
Authenticator/Source/TokenList.swift
Authenticator/Source/TokenListViewController.swift
Authenticator/Source/TokenRowCell.swift
Authenticator/Source/TokenRowModel.swift

Remove `Equatable` conformance from `TokenList.Action` and `TokenRowModel`. These `==` implementations were verbose, difficult to maintain, and incorrect for enum cases with non-equatable associated values.
The equality comparisons provided a small optimization to diffing and updating the token list table view, but performance of the new code is not measurably worse than the old.

Remove view model equatability

---

Authenticator/Source/TextFieldRow.swift

The Swift limitation that `TextFieldRowCellDelegateAdapter` was used to work around seems to no longer be present in Swift 2.2.

Remove unnecessary UITextFieldDelegate shim

---

Authenticator/Source/TableDiff.swift
Authenticator/Source/TokenFormViewController.swift
Authenticator/Source/TokenListViewController.swift

The current diffing algorithm doesn't consolidate matching Inserts and Deletes into Moves, so this case was unused. Since the current uses of the diff-and-update don't involve any moves, adding complexity to support the Move case seems unnecessary at this point in time.

Remove the Move case from the table diff Change enum

---

Authenticator/Source/AppController.swift
Authenticator/Source/TokenStore.swift

If the token store fails to load, the app will be unusable.
With this change, if persistent tokens cannot be loaded from the keychain, the `TokenStore` initializer will throw an error and the `AppController` will respond with a `fatalError`. Crashing the app is not ideal, but it is preferable to presenting the user with an unusable interface, and it should result in crash reports being sent to iTunes Connect.

Token load failure

---

Authenticator/Source/TokenListViewController.swift

Prevents the cell from having two animations scheduled during a tableView.beginUpdates pass.
In the case where a `Change` is just an update and the cell doesn't actually move positions, it's not necessary to call `reloadRowsAtIndexPaths`. When reordering a cell can potentially have two different animations scheduled which causes the crash in #135.
```
2016-10-10 09:40:52.195995 Authenticator[3852:1015298] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempt to create two animations for cell'
```

Removes reloads for cell updates

---

Authenticator/Source/TokenListViewController.swift

See #136
Not necessarily the ideal fix but shows where the problem is, namely updating
the UITableView with animated cell changes while scrolling the table view.
This reduces the changes to see if any of them require inserts, updates, or changes in cell positions. If none of the cell positions actually change we don't need to do the table animations.
From `UITableView` docs (emphasis mine):
> Reloading a row causes the table view to ask its data source for a new cell for that row. The table animates that new cell in as it animates the old row out. Call this method if you want to alert the user that the value of a cell is changing. *If, however, notifying the user is not important—that is, you just want to change the value that a cell is displaying—you can get the cell for a particular row …

Updates ring while scrolling the table view

---

Authenticator/Source/TokenListViewController.swift

This PR modifies #137 to *always* apply row `Update`s outside of the animated table view updates group. This reduces code complexity while also ensuring the "after" row indexes used for updates are referencing the correct rows after any insertions and deletions are completed.
Fixes #136.

Update ring while scrolling and avoid unnecessary table animations

---

Authenticator/Source/TokenListViewController.swift

If one or more tokens are inserted, the inserted row with the smallest row index (highest visually in the table) will be scrolled into view using the minimum amount of scrolling necessary.

Scrolls the token list to show a newly inserted token

---

Authenticator/Resources/Info.plist

From the [App Programming Guide for iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/ExpectedAppBehaviors/ExpectedAppBehaviors.html#//apple_ref/doc/uid/TP40007072-CH3-SW6):
> **Important:** When your app attempts to use a protected item, the system prompts the user with an alert asking for permission for access. Starting in iOS 10, your Info.plist file must include a purpose string, for display in the permission alert, for each such item. If your app attempts to access a protected item without you having provided a corresponding purpose string, your app exits.
The current build of the app in the app store doesn't crash on iOS 10, but any new build of the app must have an explanation of camera usage to avoid crashing.

Add NSCameraUsageDescription to the Info.plist

---

.codecov.yml
.travis.yml
Authenticator.xcodeproj/project.pbxproj
Authenticator.xcodeproj/xcshareddata/xcschemes/Authenticator.xcscheme
README.md

Generate code coverage reports when testing, send them from Travis CI to Codecov, ignore coverage of the test code itself, and display a coverage badge in the Readme.

Add code coverage reporting

---

Authenticator/Source/TokenListViewController.swift

Prevents table reloads from other actions that don't change the tokens listed
Fixes #147

Reloads tableview only when there are changes to token list

---

Authenticator/Source/TokenListViewController.swift

Use super.init(nibName:bundle:) to avoid an iOS 8 crash

---

Authenticator.xcodeproj/project.pbxproj
Authenticator/Resources/Info.plist
fastlane/Fastfile

For fastlane `beta` and `release`, generate a build number based on the number of git commits, and then clear this build number after the build is uploaded. The build number is still used to tag betas, but is not committed.

Build numbers
